In [1]:
!pip install psycopg2

Requirement already satisfied: psycopg2 in e:\users\abdul\appdata\local\programs\python\python38\lib\site-packages (2.9.4)

[notice] A new release of pip available: 22.2.2 -> 22.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
data = pd.read_csv(r"E:\Users\abdul\Desktop\new project\prescription\Copy of data123.csv")

E:\Users\abdul\AppData\Local\Temp\ipykernel_12816\393714055.py:2: DtypeWarning: Columns (0,1,2,21,22,23,24,25,26,27,28) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(r"E:\Users\abdul\Desktop\new project\prescription\Copy of data123.csv")

In [3]:
data.shape

(209994, 29)

In [4]:
location = data.drop(['YEAR_MONTH', 'YEAR', 'MONTH', 
       'PRACTICE_NAME', 'PRACTICE_CODE','BNF_CHEMICAL_SUBSTANCE',
       'CHEMICAL_SUBSTANCE_BNF_DESCR', 'BNF_CODE', 'BNF_DESCRIPTION',
       'BNF_CHAPTER_PLUS_CODE', 'QUANTITY', 'ITEMS', 'TOTAL_QUANTITY',
       'ADQUSAGE', 'NIC', 'ACTUAL_COST', 'UNIDENTIFIED', 'SNOMED_CODE'],axis=1)

In [55]:
location.duplicated()
df.groupby(df.columns.tolist(),as_index=False).size()

0         False
1         False
2         False
3         False
4         False
          ...
209989    False
209990    False
209991    False
209992    False
209993    False
Length: 209994, dtype: bool

In [56]:
import numpy as np
#location.insert(0, 'LOCATION_KEY', range(100000, 100000 + len(location)))

LOCATION_KEY = []
for i in range(1,len(location)+1):
    if(i<10):
        LOCATION_KEY.append('L000000'+str(i))
    elif(10<=i and i<100):
       LOCATION_KEY.append('L00000'+str(i))
    elif(100<=i and i<1000):
       LOCATION_KEY.append('L0000'+str(i))
    elif(1000<=i and i<10000):
       LOCATION_KEY.append('L000'+str(i))
    elif(10000<=i and i<100000):
       LOCATION_KEY.append('L00'+str(i))
    else:
       LOCATION_KEY.append('L0'+str(i))
location['LOCATION_KEY'] = pd.Series(LOCATION_KEY, index=location.index)
#trans_dim['bank_name'] = trans_dim['bank_name'].str.strip()
# trans_dim.reset_index()

In [57]:
location

,LOCATION_KEY,REGIONAL_OFFICE_NAME,REGIONAL_OFFICE_CODE,STP_NAME,STP_CODE,PCO_NAME,PCO_CODE,ADDRESS_1,ADDRESS_2,ADDRESS_3,ADDRESS_4,POSTCODE
0,L0000001,NORTH WEST,Y62,CHESHIRE & MERSEYSIDE STP,QYG,KNOWSLEY CCG,01J00,ST.LAURENCE'S MEDICAL CTR,32 LEESIDE AVENUE,"SOUTHDENE,KIRKBY",LIVERPOOL,L32 9QU
1,L0000002,NORTH WEST,Y62,CHESHIRE & MERSEYSIDE STP,QYG,KNOWSLEY CCG,01J00,ST.LAURENCE'S MEDICAL CTR,32 LEESIDE AVENUE,"SOUTHDENE,KIRKBY",LIVERPOOL,L32 9QU
2,L0000003,NORTH WEST,Y62,CHESHIRE & MERSEYSIDE STP,QYG,KNOWSLEY CCG,01J00,ST.LAURENCE'S MEDICAL CTR,32 LEESIDE AVENUE,"SOUTHDENE,KIRKBY",LIVERPOOL,L32 9QU
3,L0000004,NORTH WEST,Y62,CHESHIRE & MERSEYSIDE STP,QYG,WARRINGTON CCG,2.00E+00,STOCKTON HEATH MED.CENTRE,"THE FORGE,LONDON ROAD",STOCKTON HEATH,"WARRINGTON,CHESHIRE",WA4 6HJ
4,L0000005,NORTH WEST,Y62,CHESHIRE & MERSEYSIDE STP,QYG,WARRINGTON CCG,2.00E+00,STOCKTON HEATH MED.CENTRE,"THE FORGE,LONDON ROAD",STOCKTON HEATH,"WARRINGTON,CHESHIRE",WA4 6HJ
...,...,...,...,...,...,...,...,...,...,...,...,...
209989,L0209990,NORTH WEST,Y62,NHS CHESHIRE AND MERSEYSIDE INTEGRATED C,QYG,NHS CHESHIRE AND MERSEYSIDE ICB - 01V,01V00,CHAPEL LANE SURGERY,"13 CHAPEL LANE, FORMBY",LIVERPOOL,MERSEYSIDE,L37 4DL
209990,L0209991,NORTH WEST,Y62,NHS CHESHIRE AND MERSEYSIDE INTEGRATED C,QYG,NHS CHESHIRE AND MERSEYSIDE ICB - 01V,01V00,THE GRANGE SURGERY,41 YORK ROAD,"BIRKDALE, SOUTHPORT",MERSEYSIDE,PR8 2AD
209991,L0209992,NORTH WEST,Y62,NHS CHESHIRE AND MERSEYSIDE INTEGRATED C,QYG,NHS CHESHIRE AND MERSEYSIDE ICB - 01V,01V00,CUMBERLAND HOUSE,58 SCARISBRICK NEW ROAD,SOUTHPORT,MERSEYSIDE,PR8 6PG
209992,L0209993,NORTH WEST,Y62,NHS CHESHIRE AND MERSEYSIDE INTEGRATED C,QYG,NHS CHESHIRE AND MERSEYSIDE ICB - 01V,01V00,117 FYLDE ROAD,MARSHSIDE,SOUTHPORT,NaN,PR9 9XL
209993,L0209994,NORTH WEST,Y62,NHS CHESHIRE AND MERSEYSIDE INTEGRATED C,QYG,NHS CHESHIRE AND MERSEYSIDE ICB - 01X,01X00,RAINBOW MEDICAL CENTRE,"333 ROBINS LANE, SUTTON",ST. HELENS,MERSEYSIDE,WA9 3PN

In [38]:
import psycopg2
import pandas as pd
import psycopg2.extras

In [39]:
location['LOCATION_KEY']=location['LOCATION_KEY'].apply(str)

In [40]:
class PostgresConnection(object):
    def __init__(self):
        self.connection = psycopg2.connect(database="presdb",
                                           user = "postgres",
                                           password = "01873816816",
                                           host = "127.0.0.1",
                                           port = "5432")

    def getConnection(self):
        print("Connection to DB established!")
        return self.connection
con = PostgresConnection().getConnection()

Connection to DB established!

In [41]:
con = PostgresConnection().getConnection()
insert_stmt = "INSERT INTO snow.location(LOCATION_KEY,REGIONAL_OFFICE_NAME, REGIONAL_OFFICE_CODE, STP_NAME, STP_CODE,PCO_NAME, PCO_CODE, ADDRESS_1, ADDRESS_2, ADDRESS_3,ADDRESS_4, POST_CODE)"\
       "VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)"
cur = con.cursor()
psycopg2.extras.execute_batch(cur, insert_stmt, location.values)
con.commit()
cur.close()

Connection to DB established!

In [42]:
location.values

array([['L000001', 'NORTH WEST', 'Y62', ..., 'SOUTHDENE,KIRKBY',
        'LIVERPOOL', 'L32 9QU'],
       ['L000002', 'NORTH WEST', 'Y62', ..., 'SOUTHDENE,KIRKBY',
        'LIVERPOOL', 'L32 9QU'],
       ['L000003', 'NORTH WEST', 'Y62', ..., 'SOUTHDENE,KIRKBY',
        'LIVERPOOL', 'L32 9QU'],
       ...,
       ['L209992', 'NORTH WEST', 'Y62', ..., 'SOUTHPORT', 'MERSEYSIDE',
        'PR8 6PG'],
       ['L209993', 'NORTH WEST', 'Y62', ..., 'SOUTHPORT', nan, 'PR9 9XL'],
       ['L209994', 'NORTH WEST', 'Y62', ..., 'ST. HELENS', 'MERSEYSIDE',
        'WA9 3PN']], dtype=object)

In [43]:
location.dtypes

LOCATION_KEY            object
REGIONAL_OFFICE_NAME    object
REGIONAL_OFFICE_CODE    object
STP_NAME                object
STP_CODE                object
PCO_NAME                object
PCO_CODE                object
ADDRESS_1               object
ADDRESS_2               object
ADDRESS_3               object
ADDRESS_4               object
POSTCODE                object
dtype: object

In [96]:
bnf_chemical=data.drop(['YEAR_MONTH','YEAR', 'MONTH', 
       'REGIONAL_OFFICE_NAME','REGIONAL_OFFICE_CODE', 'STP_NAME', 'STP_CODE', 'PCO_NAME', 'PCO_CODE',
       'PRACTICE_NAME', 'PRACTICE_CODE', 'ADDRESS_1', 'ADDRESS_2', 'ADDRESS_3',
       'ADDRESS_4', 'POSTCODE', 'BNF_CODE', 'BNF_DESCRIPTION',
       'BNF_CHAPTER_PLUS_CODE', 'QUANTITY', 'ITEMS', 'TOTAL_QUANTITY',
       'ADQUSAGE', 'NIC', 'ACTUAL_COST', 'UNIDENTIFIED', 'SNOMED_CODE'],axis=1)

bnf_chemical

       BNF_CHEMICAL_SUBSTANCE              CHEMICAL_SUBSTANCE_BNF_DESCR
0                   0212000AA                      Rosuvastatin calcium
1                   0407010N0  Co-dydramol (Dihydrocodeine/paracetamol)
2                    1.00E+06                                  Etodolac
3                   0105010B0                     Mesalazine (Systemic)
4                   0206010K0                    Isosorbide mononitrate
...                       ...                                       ...
209989              0906040G0                            Colecalciferol
209990                   2010                    Surgical Adhesive Tape
209991              0407042Q0                          Pizotifen malate
209992              0208020Z0                                  Apixaban
209993              0407020Q0                          Morphine sulfate

[209994 rows x 2 columns]

<bound method DataFrame.drop_duplicates of        BNF_CHEMICAL_SUBSTANCE              CHEMICAL_SUBSTANCE_BNF_DESCR
0                   0212000AA                      Rosuvastatin calcium
1                   0407010N0  Co-dydramol (Dihydrocodeine/paracetamol)
2                    1.00E+06                                  Etodolac
3                   0105010B0                     Mesalazine (Systemic)
4                   0206010K0                    Isosorbide mononitrate
...                       ...                                       ...
209989              0906040G0                            Colecalciferol
209990                   2010                    Surgical Adhesive Tape
209991              0407042Q0                          Pizotifen malate
209992              0208020Z0                                  Apixaban
209993              0407020Q0                          Morphine sulfate

[209994 rows x 2 columns]>

In [99]:
con = PostgresConnection().getConnection()
insert_stmt = "INSERT INTO snow.bnf_chemical(BNF_CHEMICAL_SUBSTANCE,CHEMICAL_SUBSTANCE_BNF_DESC)"\
"VALUES (%s,%s)"
cur = con.cursor()
psycopg2.extras.execute_batch(cur, insert_stmt, bnf_chemical.values)
con.commit()
cur.close()

Connection to DB established!

UniqueViolation: duplicate key value violates unique constraint "pk_1"
DETAIL:  Key (bnf_chemical_substance)=(2101) already exists.

In [81]:
prescription=data.drop(['YEAR_MONTH', 'YEAR', 'MONTH','PRACTICE_NAME', 'PRACTICE_CODE', 'CHEMICAL_SUBSTANCE_BNF_DESCR','ITEMS', 'TOTAL_QUANTITY',
       'ACTUAL_COST','REGIONAL_OFFICE_NAME', 'REGIONAL_OFFICE_CODE', 'STP_NAME','UNIDENTIFIED', 'STP_CODE','PCO_NAME','PCO_CODE','ADDRESS_1', 'ADDRESS_2', 'ADDRESS_3','ADDRESS_4', 'POSTCODE'],axis=1)

In [82]:
PRESCRIPTION_KEY = []
for i in range(1,len(prescription)+1):
    if(i<10):
       PRESCRIPTION_KEY.append('P000000'+str(i))
    elif(10<=i and i<100):
       PRESCRIPTION_KEY.append('P00000'+str(i))
    elif(100<=i and i<1000):
       PRESCRIPTION_KEY.append('P0000'+str(i))
    elif(1000<=i and i<10000):
      PRESCRIPTION_KEY.append('P000'+str(i))
    elif(10000<=i and i<100000):
      PRESCRIPTION_KEY.append('P00'+str(i))
    else:
       PRESCRIPTION_KEY.append('P0'+str(i))
prescription['PRESCRIPTION_KEY'] = pd.Series(PRESCRIPTION_KEY, index=prescription.index)

In [83]:
prescription.columns

Index(['BNF_CHEMICAL_SUBSTANCE', 'BNF_CODE', 'BNF_DESCRIPTION',
       'BNF_CHAPTER_PLUS_CODE', 'QUANTITY', 'ADQUSAGE', 'NIC', 'SNOMED_CODE',
       'PRESCRIPTION_KEY'],
      dtype='object')

In [84]:
prescription

,BNF_CHEMICAL_SUBSTANCE,BNF_CODE,BNF_DESCRIPTION,BNF_CHAPTER_PLUS_CODE,QUANTITY,ADQUSAGE,NIC,SNOMED_CODE,PRESCRIPTION_KEY
0,0212000AA,0212000AAAAADAD,Rosuvastatin 5mg tablets,02: Cardiovascular System,28.0,14.0,1.52,409108001.0,P0000001
1,0407010N0,0407010N0BGABAI,Remedeine Forte tablets,04: Central Nervous System,200.0,700.0,341.04,420000000000000.0,P0000002
2,1.00E+06,1001010E0AAADAD,Etodolac 600mg modified-release tablets,10: Musculoskeletal and Joint Diseases,28.0,28.0,14.47,39100000000000000.0,P0000003
3,0105010B0,0105010B0BIABAA,Octasa 400mg MR gastro-resistant tablets,01: Gastro-Intestinal System,168.0,42.0,30.94,21400000000000000.0,P0000004
4,0206010K0,0206010K0BNACAE,Isib 60XL tablets,02: Cardiovascular System,14.0,0.0,4.08,717000000000000.0,P0000005
...,...,...,...,...,...,...,...,...,...
209989,0906040G0,0906040G0BRABBW,Calcichew D3 Forte chewable tablets,09: Nutrition and Blood,60.0,0.0,46.68,45600000000000.0,P0209990
209990,2010,20100000532,Micropore tape 2.5cm,20: Dressings,10.0,0.0,3.72,522000000000000.0,P0209991
209991,0407042Q0,0407042Q0AAACAC,Pizotifen 1.5mg tablets,04: Central Nervous System,56.0,560.0,4.34,322850007.0,P0209992
209992,0208020Z0,0208020Z0AAAAAA,Apixaban 2.5mg tablets,02: Cardiovascular System,14.0,0.0,53.2,703907006.0,P0209993
209993,0407020Q0,0407020Q0BBAKCG,MST Continus 5mg tablets,04: Central Nervous System,30.0,1.5,1.65,922000000000000.0,P0209994

In [93]:
con = PostgresConnection().getConnection()
insert_stmt = "INSERT INTO snow.prescription(BNF_CHEMICAL_SUBSTANCE, BNF_CODE, BNF_DESCRIPTION,BNF_CHAPTER_PLUS_CODE, QUANTITY, ADQUSAGE,NIC,SNOMED_CODE,PRESCRIPTION_KEY)"\
"VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s)"
cur = con.cursor()
psycopg2.extras.execute_batch(cur, insert_stmt, prescription.values)
con.commit()
cur.close()

Connection to DB established!

ForeignKeyViolation: insert or update on table "prescription" violates foreign key constraint "fk_4"
DETAIL:  Key (bnf_chemical_substance)=(0212000AA) is not present in table "bnf_chemical".

In [ ]:
time = data.drop(['YEAR_MONTH','REGIONAL_OFFICE_NAME',
       'REGIONAL_OFFICE_CODE', 'STP_NAME', 'STP_CODE', 'PCO_NAME', 'PCO_CODE',
       'PRACTICE_NAME', 'PRACTICE_CODE', 'ADDRESS_1', 'ADDRESS_2', 'ADDRESS_3',
       'ADDRESS_4', 'POSTCODE', 'BNF_CHEMICAL_SUBSTANCE',
       'CHEMICAL_SUBSTANCE_BNF_DESCR', 'BNF_CODE', 'BNF_DESCRIPTION',
       'BNF_CHAPTER_PLUS_CODE', 'QUANTITY', 'ITEMS', 'TOTAL_QUANTITY',
       'ADQUSAGE', 'NIC', 'ACTUAL_COST', 'UNIDENTIFIED', 'SNOMED_CODE'], axis =1)

In [ ]:
df = pd.DataFrame(time)
time_df = df.drop_duplicates()
time_df

In [ ]:
time_key = []
for i in range(1,len(time_df)+1):
    if(i<10):
        time_key.append('T00'+str(i))
    else:
        time_key.append('T0'+str(i))
time_df['TIME_KEY'] = pd.Series(time_key, index=time_df.index)
time_df